(define (problem cargo-4-2-2)
(:domain cargo)
(:objects loc4 loc3 loc2 loc1 tru2 tru1 crg4 crg3 crg2 crg1 drv1 drv2 cat1 cat2)
(:init (cargo crg1) (cargo crg2) (cargo crg3) (cargo crg4) 
 (truck tru1) (truck tru2)
 (driver drv1) (driver drv2)
 (category cat1) (category cat2)
 (location loc1) (location loc2) (location loc3) (location loc4)
 (at tru1 loc1) (at tru2 loc2) 
 (at drv1 loc1) (at drv2 loc2)
 (at crg1 loc1) (at crg2 loc2) (at crg3 loc3) (at crg4 loc4)

 (compatible tru1 cat1) (compatible tru2 cat2) 
 (compatible drv1 cat1) (compatible drv2 cat2)
 (compatible crg1 cat1) (compatible crg2 cat2) (compatible crg3 cat1) (compatible crg4 cat2)
 (= (total-cost) 0))
(:goal (and (at crg1 loc3) (at crg2 loc4) (at crg3 loc1) 
            (at crg4 loc2)))
(:metric minimize (total-cost))
)